name: LightSpark CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: cd Backend && npm install
        
      - name: Run Linter
        run: cd Backend && npx eslint . || true
        
      - name: Build and Test Backend
        run: |
          cd Backend
          npm test || echo "Nenhum teste configurado"
  
  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Backend
        uses: docker/build-push-action@v4
        with:
          context: ./Backend
          push: false
          load: true
          tags: lightspark-backend:latest
          
      - name: Build Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./Frontend
          push: false
          load: true
          tags: lightspark-frontend:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
      - name: Deploy to production
        run: echo "Deploy step - configure para seu ambiente específico"